### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by rafhik** [DigiBase-VolkerWessels/SketchUp-bsDD-plugin#1]
I have installed the extension and it doesn't works in my computer. I'm working with Scketchup 2022 for Mac. My computer has M1 chip if it helps.

**Comment by janbrouwer** [comment]
Thanks for reporting this!

I don't have an Apple device to test with so that could be the cause of the problem, but there are no Windows specific parts in the extension as far as I can think of.

Can you explain a bit more about what doesn't work? Do you get loading errors? Can you share a screenshot? or the output of the ruby console?

**Comment by rafhik** [comment]
![Captura de Pantalla 2022-08-25 a las 14 44 27](https://user-images.githubusercontent.com/62211918/186668021-3486b6c9-83df-41bc-a1b9-82e0caea18a1.jpg)

Both of pannels are empty. Ruby console doesn't receive any warning

**Comment by janbrouwer** [comment]
That's strange... And if you right click on the dialog, can you get into the browser javascript console? Maybe it shows errors there? (For me in windows that's right-click "Inspect Element" and then "Console"...)

**Comment by rafhik** [comment]
No,I tried but I have no access to javascript console.

**Comment by janbrouwer** [comment]
The new release should work on Mac: https://github.com/DigiBase-VolkerWessels/SketchUp-bsDD-plugin/releases/tag/v2.1.1

**Comment by rafhik** [comment]
> The new release should work on Mac: https://github.com/DigiBase-VolkerWessels/SketchUp-bsDD-plugin/releases/tag/v2.1.1

It worked! Sorry for the delay
